### ISSUE TITLE
Detect non-existent pedestrian

### ISSUE THREAD

**Issue by hatta-yuuto** [robotics-upo/dynamic_obstacle_detector#2]
Hello.
I recently had a question on SFWPlanner. Since you said it was most likely a recognition problem, I'll ask here. When I displayed the distance to pedestrians during the simulation, the values were generally correct, but occasionally a non-existent pedestrian was detected and the distance to that pedestrian was output. I understand that this detector is a simple one, so some false positives are inevitable, but I would like to know if there are any parameters that should be changed to reduce false positives.

**Comment by noeperez** [comment]
Hello,

I am afraid that these false positives can not be avoided through the parameters. Most of the false positives are detected in walls and are provoked by the occlusions of the real dynamic obstacles. A filter based on global map could be tried. However, this detector is just for testing purposes, no improvements are planned for the moment. You will need a more reliable people detector in case these false positives are provoking an undesired behavior. 
We are working on new detectors but they won't be available soon.

**Comment by hatta-yuuto** [comment]
Thank you.
I will try filter based on global map.
