### ISSUE TITLE
Use this detector in a real environment

### ISSUE THREAD

**Issue by So-chibun** [robotics-upo/dynamic_obstacle_detector#4]
Hello.
When I try to use this detector in a real environment, I get a lot of blue dots on rviz. On the other hand, with the same parameters, in the simulated environment, blue dots are displayed only in the area where there are pedestrians. Is this detector not so suitable for the real environment? Or can it be solved by adjusting the parameters?

**Comment by noeperez** [comment]
Hello,

yes, it can be used in real environments. You just need to adjust the parameters according to the features of your laser scan, and the velocities that you want to track. The parameters are clearly explained in the documentation. 
Remember that the blue dots are just the point clusters that are candidates to be the dynamic obstacles. Only the ones that exceed a velocity threshold are considered as dynamic obstacles.

**Comment by So-chibun** [comment]
Thank you very much . One thing I want to make sure is that if the speed of the obstacle is 1.0m/s, the default parameters (max_vel_tracked 2.0,min_vel_tracked  0.35) should be used, right? Or should max_vel_tracked be a little smaller?
